### PR TITLE
Fix #840 - show notification on install or update

### LINKED ISSUE #840: Send notifications when a download is finished
Allow disabling that in 'Behavior' settings section.

### PR DESCRIPTION
**Pull request by ESWAT**
notify

Should probably update the Electron icon as well… have no tested on Windows or Linux yet.

### CODE REVIEW

**Comment by fasterthanlime** [comment]
So, in a production build, the icon will be that of the itch app — but it'd be cool if it was the game thumbnail instead, what do you think?

**Comment by ESWAT** [comment]
Hmm, I like the idea if
1. We can show the thumbnail in addition to the actual Itch icon (seems to be possible with Electron)
2. Thumbnails can look good at such small sizes. If `coverUrl` is the only icon-like image we have of games then I’d say not since they’d be so unrecognizable. I guess getting the icon of the executable is an option as well.

If both of those can’t be satisfied then I’d just stick with the Itch icon + text.

**Comment by fasterthanlime** [comment]
We're going to have to let games upload icons at some point (and/or extract them from exe, etc.) if we want to implement #864 

In the meantime, I'd say just having the itch icon for the notification is fine!

**Comment by ESWAT** [comment]
Cool, then this is ready to merge from my perspective. :)

**Comment by fasterthanlime** [comment]
How about providing an option in `Preferences` to disable that notification? :)

**Comment by ESWAT** [comment]
Ah, forgot about that! On it…

**Comment by ESWAT** [comment]
FYI this branch ready… though I noticed Preferences is broken in `master` and already rebased my commits over it in my branch so haven’t been able to test this properly.

**Comment by fasterthanlime** [comment]
> though I noticed Preferences is broken in master

Oh? it shouldn't be, let me see if I can find what you're talking about.

**Comment by fasterthanlime** [comment]
Merged!
- I fixed the changes in preferences — they were bound to the text and value of `minimize to tray`, not `ready notification`
- I made it so that clicking the notification focuses on the game instead of just popping the itch app to the front.

**Comment by ESWAT** [comment]
Ah, my bad. Thanks for taking care of that!

**Pull request merged**
