### PR TITLE
Add Spanish menu translations

### PR DESCRIPTION
**Pull request by matiasbeckerle**
Quick one @fasterthanlime. Just playing with some translations. Also fixed [this one](http://screencast.com/t/LJbzyrIpIlib). Tests are failing due to `undefined` with i18n thing. Couldn't spent time with that yet.

Put translations keys on alphabetical order but that could be changed if you disagree.

Also noticed that switching from languages produces an [issue](http://screencast.com/t/qg86LIuV).

### CODE REVIEW

**Comment by fasterthanlime** [comment]
Note that ultimately, translations won't be accepted by pull requests but
only via http://pootle.itch.ovh (I'm not done setting it up)

**Comment by matiasbeckerle** [comment]
Ohhh. Got it, thanks!

**Comment by fasterthanlime** [comment]
> undefined

I'll take a look at that

> Also noticed that switching from languages produces an issue.

That must mean a json syntax error in the en.json file. I had a similar problem.

**Comment by matiasbeckerle** [comment]
Oh should be the "Don't", my fault.

**Comment by fasterthanlime** [comment]
> Oh should be the "Don't"

Hmm maybe, http://jsonlint.com/ marks it as valid, weird. I was fully expecting the i18n backend to err when loading invalid JSON files but apparently it gracefully fails instead :|

edit: https://jsonformatter.curiousconcept.com/ marks it as invalid because of the `Don't` indeed. I'll validation just to make sure but since I was planning on using Pootle for all the actual translation I was more or less expecting `po2json` to produce valid json

**Comment by fasterthanlime** [comment]
@matiasbeckerle all merged, thanks! :star2:

**Pull request merged**
