### PR TITLE
Show helpful modal when launch using java fails

### LINKED ISSUE #945: For .jar, check for java presence, tell user to install if not there
see https://github.com/itchio/itch-compatibility-watchlist/issues/215

### PR DESCRIPTION
**Pull request by ESWAT**
WIP but Fixes #945.

Could use a button that pops an external window for the user to download Java, and some new translations for game.install.could_not_launch.missing_jre

Feedback welcome :)

screen shot 2016-11-03 at 13 27 19

### CODE REVIEW

**Comment by fasterthanlime** [comment]
Looks like a good start!

I have one bit of feedback about the code that's already in: the error code will depend on the platform. I think `ENOENT` might work for Linux/macOS, but I have a feeling it won't work on Windows.

Instead, we could write a piece of code that navigates `$PATH`/`%PATH`, looking for `java`/`java.exe`, and errs if it can't find it. This way, we could catch the error even before it happens — and do that check only when we're supposed to launch with java :)

> Could use a button that pops an external window for the user to download Java

Definitely agree with that! However, I think the advice should be os-specific: for Linux, maybe we could have some distro-specific instructions?

> and some new translations for game.install.could_not_launch.missing_jre

This will happen over time via https://weblate.itch.ovh/ :)

**Comment by ESWAT** [comment]
Forgot to mention that I checked the error code in Windows and it’s the same. However your solution is more robust so I’ll try to put that in. :)

**Comment by ESWAT** [comment]
I changed the behaviour so it looks for the system JRE using (which)[https://www.npmjs.com/package/which] when we detected the `.jar` file in `native.ts`. If there’s no exception then we just keep going, otherwise we display a modal with a message and button that launches https://www.java.com/en/download/ in an external browser.

screen shot 2016-11-07 at 11 36 41

I’m using `which` instead of just checking the path myself since it was easier to use this to find the java executable in the path.

My writing for this isn’t the greatest though…

**Comment by ESWAT** [comment]
I still need to test this new behaviour on Windows also.

**Pull request merged**
