### PR TITLE
Preferences (WIP)

### PR DESCRIPTION
**Pull request by matiasbeckerle**
:construction: WIP

Hi @fasterthanlime. I'm opening this PR prematurely in order to discuss how we are going to solve some issues regarding a preferences implementation. This is not ready-for-review.

TODO:
- [X] Add preferences section.
- [X] Include preferences on main menu.
- [X] Save language preference.
- [X] Add language wrapper for i18n module. 
- [X] Add "select" (form) for language selection in preferences.
- [ ] Apply or restart on saving for the new language?
- [ ] Style.
- [ ] Icons (save & cancel not available yet).
- [ ] Add tests.
- [ ] Add translations.
- [ ] Translate as much as possible.

### CODE REVIEW

**Comment by fasterthanlime** [comment]
Early PRs are a good thing, and a preference pane is overdue. I'll take a look at this soon!

**Comment by matiasbeckerle** [comment]
First question. In `util/db.js` there is a load method that creates a user directory based on itch.io user credentials instead of OS user. Which approach should I use for the preferences?

**Comment by matiasbeckerle** [comment]
Second question. Is there any "simple" preference to add? This question is in order to have a merge sooner instead of working on the library directories complexity.

**Comment by matiasbeckerle** [comment]
I'm working pretty slow here (because several reasons) but feel free to use this WIP in any way if you are in a hurry to get preferences working soon. In the meantime I will try to make some progress.

**Comment by matiasbeckerle** [comment]
Hi @fasterthanlime. Going to make i18n for the first preference instead of handling paths.

**Comment by fasterthanlime** [comment]
> Going to make i18n for the first preference instead of handling paths.

@matiasbeckerle seems like a good idea. There's also some data collection preferences to expose but it's probably not just a single checkbox

**Comment by matiasbeckerle** [comment]
If you download my latest commit @fasterthanlime, you can see something in progress. Suggestions, code improvements, conventions, everything is welcomed!

**Comment by fasterthanlime** [comment]
@matiasbeckerle I'm currently fighting pretty hard to set up deb/rpm repos for the next 0.11.x release, but no worries, I shall take a look :)

**Comment by matiasbeckerle** [comment]
Of course!!! don't worry @fasterthanlime!

**Comment by fasterthanlime** [comment]
Hey @matiasbeckerle, I rebased your PR against 0.11.3 and started working on it in my own branch: https://github.com/itchio/itch/tree/preferences-and-install-location

I'd like the preferences dialog to be a pop-up, not a different 'page' of the app. Or it could be a tab. Hmm.

For i18n, I've had my mind set on http://i18next.com/ — I want a translation server (almost done setting up pootle) and for changes to be applied instantly, with https://github.com/i18next/react-i18next

I think we need a way to have persistent tabs in the sidebar & for them to display stuff that's not a LibraryContent / GameList

**Comment by matiasbeckerle** [comment]
Awesome @fasterthanlime! I'm reviewing your changes in order to make better contributions in the future... also learning from my mistakes.

I'm closing this PR because you are taking the lead now.

BTW really sorry about the line-ending thing. I was completely sure I had the .editorconfig plugin installed but it wasn't... #shame #shame #shame.

**Comment by fasterthanlime** [comment]
> I'm reviewing your changes

Don't hesitate to ask any questions about it — documentation is still severely lacking on the internal codebase, and some of the changes I'm making are non-obvious.

For example, why should `i18n` be a store rather than simply a `util` module ?

`util` modules are usually a bunch of functions (async or not) that are used independently, for different purposes, by the rest of the application.

stores are the guardian of a little bit of state that's global to the application: throughout the application, at one given time, we're always using a single language — and we only need a single i18next instance to translate our strings.

when we change the language, it makes sense to have a single place where it's changed (I18nStore) and then dispatched (via `emit_change`) to all subscribers (like ui/menu, tray-store, window-store, but also renderer-side things like our React app).

anyone reading this should really read up on how the [Flux pattern](https://facebook.github.io/flux/docs/overview.html) works, basically:
- when you want to do something, send an **app action** via the (singleton) dispatcher
- have stores react to the actions you care about, and change their internal state
- when a store changes their internal state, have them send an event to your subscribers

Only stores have write-access to their state, everybody else just has read-only.

Even less trivial are the subtle distinctions between 'browser-side' (node.js) and 'renderer-side' (Chromium). Most stores either live on one side or the other. For example, `game-store` handles API requests, it leaves on the `browser/node.js` side. Whereas `app-store`, which maintains the state of the React app, lives on the `renderer/Chromium` side.

For i18n, there's actually two stores, each on one side, which is wasteful at load/languageChange-time, but optimal at run-time, since there is no need for RPC (remote procedure call) between the browser & renderer side (which is blocking, and would kill the app's performance).

> I'm closing this PR because you are taking the lead now.

There'll definitely be a time to jump back in soon!

> BTW really sorry about the line-ending thing

It's absolutely no big deal. A few other files were caught with CRLF line endings too, I work on windows sometimes :)

**Comment by matiasbeckerle** [comment]
Thank you very much @fasterthanlime. I'm new into React and Electron so I'm reading everything I can. Your flux pattern link is really helpful. I will dig into that after work. Thank you again for the whole explanation :)

**Pull request closed without merging**
