### PR TITLE
Prevent display sleep while playing

### PR DESCRIPTION
**Pull request by quyse**
That's for #1139
* add setting in preferences
* prevent display sleep for native games
* use preference setting when launching html games too

### CODE REVIEW

**Comment by GranPC** [comment]
Just one super tiny nitpick -- we usually leave a space after 'if' statements (so they would look like ```if (blockerId !== null) {```). Other than that though, great job! :+1:

**Comment by quyse** [comment]
@GranPC Fixed :D I'll try to follow the established code style in future.

**Comment by fasterthanlime** [comment]
I'm looking at this entirely too late, and I'm thinking: there's a single "launch" task, can't we re-use some code here? I feel bad about having it duplicated between `launch/html` and `launch/native`

**Comment by quyse** [comment]
@fasterthanlime Moved display sleep blocking code into `launch` task, so it's not duplicated anymore. Seems still working :)

**Comment by fasterthanlime** [comment]
Merged! thanks a bunch @quyse :)

**Pull request merged**
